#!/usr/bin/env bash
# ==============================================================================
# 🧹 Agentic-AI: Demo Content Cleanup Utility
# ==============================================================================
# Usage:
#   ./cleanup_demo.sh             -> Interactive cleanup menu
#   ./cleanup_demo.sh --workspace -> Clean files generated in workspace/
#   ./cleanup_demo.sh --reports   -> Clean evaluation reports generated by demo
#   ./cleanup_demo.sh --db        -> Purge demo test sessions from SQLite databases
#   ./cleanup_demo.sh --logs      -> Reset gateway and webui demo logs
#   ./cleanup_demo.sh --stop      -> Stop running demo background services
#   ./cleanup_demo.sh --all       -> Clean workspace, reports, demo DB records, and logs
#   ./cleanup_demo.sh --purge     -> Full purge (stops services, cleans all demo data & files)
#   ./cleanup_demo.sh --help      -> Show help message
# ==============================================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Formatting Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

# Activate Python virtual environment if present
if [ -d "$SCRIPT_DIR/.venv" ]; then
    source "$SCRIPT_DIR/.venv/bin/activate"
fi

print_banner() {
    echo -e "${CYAN}${BOLD}"
    echo "=========================================================================="
    echo "  🧹 AGENTIC-AI : DEMO CLEANUP UTILITY"
    echo "  Clean Workspace Artifacts · Purge Demo DB Records · Reset Test Logs"
    echo "=========================================================================="
    echo -e "${NC}"
}

# ------------------------------------------------------------------------------
# 1. Clean Workspace Generated Files
# ------------------------------------------------------------------------------
clean_workspace() {
    echo -e "${BLUE}📂 Cleaning demo-generated files in workspace/...${NC}"
    local count=0
    
    # Specific known demo artifacts
    DEMO_FILES=(
        "paris_trip_checklist.txt"
        "paris_weekend_itinerary.md"
        "grocery_and_recipe_guide.md"
        "corporate_expense_report.json"
        "demo_notes.txt"
        "eval_test.txt"
        "system_report.txt"
    )

    for f in "${DEMO_FILES[@]}"; do
        if [ -f "$SCRIPT_DIR/workspace/$f" ]; then
            rm -f "$SCRIPT_DIR/workspace/$f"
            echo -e "  ${GREEN}✓ Removed workspace/$f${NC}"
            count=$((count + 1))
        fi
    done

    # Remove any test files created by tools or evaluations
    find "$SCRIPT_DIR/workspace" -maxdepth 1 -type f \( -name "test_*" -o -name "demo_*" -o -name "*_temp.*" \) | while read -r p; do
        rm -f "$p"
        echo -e "  ${GREEN}✓ Removed $(basename "$p")${NC}"
        count=$((count + 1))
    done

    if [ $count -eq 0 ]; then
        echo -e "  ${YELLOW}No temporary demo files found in workspace/.${NC}"
    else
        echo -e "  ${GREEN}✓ Cleaned $count workspace file(s).${NC}"
    fi
}

# ------------------------------------------------------------------------------
# 2. Clean Evaluation Reports
# ------------------------------------------------------------------------------
clean_reports() {
    echo -e "${BLUE}📊 Cleaning untracked demo benchmark reports in evals_framework/reports/...${NC}"
    local count=0
    if [ -d "$SCRIPT_DIR/evals_framework/reports" ]; then
        # Only remove untracked reports (created during current demo runs)
        git status --porcelain "$SCRIPT_DIR/evals_framework/reports" 2>/dev/null | grep "^??" | awk '{print $2}' | while read -r r; do
            if [ -f "$r" ]; then
                rm -f "$r"
                echo -e "  ${GREEN}✓ Removed untracked $(basename "$r")${NC}"
                count=$((count + 1))
            fi
        done
    fi

    if [ $count -eq 0 ]; then
        echo -e "  ${YELLOW}No untracked benchmark reports found to clean.${NC}"
    else
        echo -e "  ${GREEN}✓ Cleaned $count untracked evaluation report(s).${NC}"
    fi
}

# ------------------------------------------------------------------------------
# 3. Clean Video Recordings
# ------------------------------------------------------------------------------
clean_recordings() {
    echo -e "${BLUE}🎥 Cleaning demo video and audio recordings in recordings/...${NC}"
    local count=0
    if [ -d "$SCRIPT_DIR/recordings" ]; then
        find "$SCRIPT_DIR/recordings" -type f \( -name "*.webm" -o -name "*.mp4" -o -name "*.aiff" -o -name "*.wav" \) | while read -r f; do
            rm -f "$f"
            echo -e "  ${GREEN}✓ Removed $(basename "$f")${NC}"
            count=$((count + 1))
        done
        find "$SCRIPT_DIR/recordings" -type d -name ".temp_*" -exec rm -rf {} + 2>/dev/null || true
    fi

    if [ $count -eq 0 ]; then
        echo -e "  ${YELLOW}No temporary demo video recordings found in recordings/.${NC}"
    else
        echo -e "  ${GREEN}✓ Cleaned recording(s).${NC}"
    fi
}

# ------------------------------------------------------------------------------
# 4. Purge Demo Records from SQLite Databases
# ------------------------------------------------------------------------------
clean_db() {
    echo -e "${BLUE}💾 Purging demo session records from SQLite databases...${NC}"
    python3 - << 'EOF'
import sqlite3
import os
from pathlib import Path

base_dir = Path(".").resolve()
gateway_db = base_dir / "llm_gateway.db"
kg_db = base_dir / "memory_store" / "knowledge_graph.db"
mem_db = base_dir / "memory_store" / "memories.db"
test_mem = base_dir / "test_mem.db"

# 1. Clean test_mem.db
if test_mem.exists():
    try:
        test_mem.unlink()
        print("  ✓ Removed temporary test_mem.db")
    except Exception as e:
        print(f"  ✗ Failed to delete test_mem.db: {e}")

# 2. Clean llm_gateway.db demo sessions
if gateway_db.exists():
    try:
        conn = sqlite3.connect(gateway_db)
        cur = conn.cursor()
        
        # Check tables
        tables = [r[0] for r in cur.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()]
        
        deleted_logs = 0
        deleted_turns = 0
        deleted_sessions = 0
        deleted_hitl = 0
        
        if "llm_logs" in tables:
            cur.execute("DELETE FROM llm_logs WHERE session_id LIKE 'everyday_sess_%' OR caller_id LIKE '%demo%' OR caller_id LIKE '%everyday%' OR conversation_id LIKE '%paris%' OR conversation_id LIKE '%demo%'")
            deleted_logs = cur.rowcount
            
        if "agent_turns" in tables:
            cur.execute("DELETE FROM agent_turns WHERE session_id LIKE 'everyday_sess_%' OR session_id LIKE 'demo_%'")
            deleted_turns = cur.rowcount
            
        if "agent_sessions" in tables:
            cur.execute("DELETE FROM agent_sessions WHERE session_id LIKE 'everyday_sess_%' OR session_id LIKE 'demo_%'")
            deleted_sessions = cur.rowcount
            
        if "hitl_requests" in tables:
            cur.execute("DELETE FROM hitl_requests WHERE request_id LIKE '%demo%' OR request_id LIKE '%delete_workspace%'")
            deleted_hitl = cur.rowcount
            
        conn.commit()
        conn.close()
        print(f"  ✓ Purged llm_gateway.db: {deleted_logs} logs, {deleted_turns} turns, {deleted_sessions} sessions, {deleted_hitl} HITL requests.")
    except Exception as e:
        print(f"  ✗ Error cleaning llm_gateway.db: {e}")

# 3. Clean demo triples from knowledge_graph.db
if kg_db.exists():
    try:
        conn = sqlite3.connect(kg_db)
        cur = conn.cursor()
        tables = [r[0] for r in cur.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()]
        if "relations" in tables and "entities" in tables:
            cur.execute("DELETE FROM relations WHERE source_entity LIKE '%Maya Lin%' OR target_entity LIKE '%GraphRAG%'")
            deleted_rel = cur.rowcount
            cur.execute("DELETE FROM entities WHERE entity_id LIKE '%Maya Lin%' OR entity_id LIKE '%Architecture Review%'")
            deleted_ent = cur.rowcount
            conn.commit()
            print(f"  ✓ Cleaned knowledge_graph.db: {deleted_rel} demo relations, {deleted_ent} demo entities.")
        conn.close()
    except Exception as e:
        print(f"  ✗ Error cleaning knowledge_graph.db: {e}")

# 4. Clean demo memories
if mem_db.exists():
    try:
        conn = sqlite3.connect(mem_db)
        cur = conn.cursor()
        tables = [r[0] for r in cur.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()]
        if "memories" in tables:
            cur.execute("DELETE FROM memories WHERE namespace='corporate_ops' OR content LIKE '%budget review is scheduled for October 15th%'")
            deleted_mem = cur.rowcount
            conn.commit()
            print(f"  ✓ Cleaned memories.db: {deleted_mem} demo corporate_ops memories.")
        conn.close()
    except Exception as e:
        print(f"  ✗ Error cleaning memories.db: {e}")
EOF
}

# ------------------------------------------------------------------------------
# 4. Clean Logs & PIDs
# ------------------------------------------------------------------------------
clean_logs() {
    echo -e "${BLUE}📜 Resetting demo runtime logs and lock files...${NC}"
    
    if [ -f "$SCRIPT_DIR/gateway.log" ]; then
        > "$SCRIPT_DIR/gateway.log"
        echo -e "  ${GREEN}✓ Truncated gateway.log${NC}"
    fi

    if [ -f "$SCRIPT_DIR/webui_dev.log" ]; then
        > "$SCRIPT_DIR/webui_dev.log"
        echo -e "  ${GREEN}✓ Truncated webui_dev.log${NC}"
    fi
}

# ------------------------------------------------------------------------------
# 5. Stop Running Services
# ------------------------------------------------------------------------------
stop_services() {
    echo -e "${YELLOW}🛑 Stopping active background services...${NC}"
    if [ -f "$SCRIPT_DIR/restart.sh" ]; then
        "$SCRIPT_DIR/restart.sh" stop >/dev/null 2>&1 || true
    fi
    echo -e "  ${GREEN}✓ Services stopped.${NC}"
}

# ------------------------------------------------------------------------------
# Clean All Demo Contents
# ------------------------------------------------------------------------------
clean_all() {
    clean_workspace
    clean_reports
    clean_recordings
    clean_db
    clean_logs
    echo -e "\n${GREEN}${BOLD}✨ All demo-generated contents have been cleanly reset!${NC}\n"
}

# ------------------------------------------------------------------------------
# Deep Purge
# ------------------------------------------------------------------------------
purge_all() {
    echo -e "${RED}${BOLD}⚠️  Performing Full Purge (Stopping Services + Cleaning Data)...${NC}\n"
    stop_services
    clean_workspace
    clean_reports
    clean_recordings
    clean_db
    clean_logs
    echo -e "\n${GREEN}${BOLD}✨ Full purge completed successfully! System is in pristine state.${NC}\n"
}

# ------------------------------------------------------------------------------
# Interactive Menu
# ------------------------------------------------------------------------------
interactive_menu() {
    print_banner
    echo -e "Please select cleanup action:"
    echo -e "  ${BOLD}1)${NC} 📂 Clean demo files in ${CYAN}workspace/${NC}"
    echo -e "  ${BOLD}2)${NC} 📊 Clean benchmark reports in ${CYAN}evals_framework/reports/${NC}"
    echo -e "  ${BOLD}3)${NC} 🎥 Clean video recordings in ${CYAN}recordings/${NC}"
    echo -e "  ${BOLD}4)${NC} 💾 Purge demo sessions from ${CYAN}SQLite databases${NC}"
    echo -e "  ${BOLD}5)${NC} 📜 Reset runtime ${CYAN}gateway.log & webui_dev.log${NC}"
    echo -e "  ${BOLD}6)${NC} 🛑 ${YELLOW}Stop running demo background services${NC}"
    echo -e "  ${BOLD}7)${NC} ✨ ${GREEN}${BOLD}Clean All Demo Data (Workspace, Reports, Videos, DB, Logs)${NC}"
    echo -e "  ${BOLD}8)${NC} 💥 ${RED}${BOLD}Full Purge (Stop services + Clean everything)${NC}"
    echo -e "  ${BOLD}q)${NC} Cancel / Quit\n"
    
    read -rp "Enter choice [1-8 or q]: " choice
    case "$choice" in
        1) clean_workspace ;;
        2) clean_reports ;;
        3) clean_recordings ;;
        4) clean_db ;;
        5) clean_logs ;;
        6) stop_services ;;
        7) clean_all ;;
        8) purge_all ;;
        q|Q) echo -e "${CYAN}Cleanup cancelled.${NC}"; exit 0 ;;
        *) echo -e "${RED}Invalid choice: $choice${NC}"; exit 1 ;;
    esac
}

# ------------------------------------------------------------------------------
# Dispatcher
# ------------------------------------------------------------------------------
case "${1:-}" in
    --workspace|-w)
        print_banner
        clean_workspace
        ;;
    --reports|-r)
        print_banner
        clean_reports
        ;;
    --recordings|--video|-v)
        print_banner
        clean_recordings
        ;;
    --db|-d)
        print_banner
        clean_db
        ;;
    --logs|-l)
        print_banner
        clean_logs
        ;;
    --stop|-s)
        print_banner
        stop_services
        ;;
    --all|-a)
        print_banner
        clean_all
        ;;
    --purge|-p)
        print_banner
        purge_all
        ;;
    --help|-h)
        print_banner
        echo "Usage: ./cleanup_demo.sh [OPTION]"
        echo ""
        echo "Options:"
        echo "  (no args)        Open the interactive cleanup menu"
        echo "  --workspace, -w  Clean demo-generated files in workspace/"
        echo "  --reports, -r    Clean benchmark reports in evals_framework/reports/"
        echo "  --recordings, -v Clean video recordings in recordings/"
        echo "  --db, -d         Purge demo sessions from SQLite databases"
        echo "  --logs, -l       Reset runtime gateway and webui logs"
        echo "  --stop, -s       Stop running demo background services"
        echo "  --all, -a        Clean workspace, reports, videos, demo DB records, and logs"
        echo "  --purge, -p      Full purge: stop services and clean all demo data"
        echo "  --help, -h       Show this help message"
        ;;
    "")
        if [ -t 0 ]; then
            interactive_menu
        else
            print_banner
            clean_all
        fi
        ;;
    *)
        echo -e "${RED}Unknown option: $1${NC}"
        echo "Run ./cleanup_demo.sh --help for available options."
        exit 1
        ;;
esac
