import React, { useState, useEffect } from 'react';
import { api } from '../api/client';
import { FileText, Plus, Save, Download, Trash2, Edit3 } from 'lucide-react';

export default function WorkspaceView() {
  const [files, setFiles] = useState([]);
  const [activeFile, setActiveFile] = useState(null);
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    loadFiles();
  }, []);

  const loadFiles = async () => {
    try {
      const data = await api.getWorkspaceFiles();
      setFiles(data.files || []);
    } catch (err) {
      console.error(err);
    }
  };

  const handleOpenFile = async (filename) => {
    setLoading(true);
    try {
      const data = await api.getWorkspaceFile(filename);
      setActiveFile(data.filename);
      setContent(data.content || '');
    } catch (err) {
      alert('Failed to read file: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleSaveFile = async () => {
    if (!activeFile) return;
    try {
      await api.saveWorkspaceFile(activeFile, content);
      alert(`Saved '${activeFile}' successfully.`);
      loadFiles();
    } catch (err) {
      alert('Failed to save: ' + err.message);
    }
  };

  const handleDownload = () => {
    if (!activeFile) return;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = activeFile;
    a.click();
  };

  const handleCreatePrompt = async () => {
    const filename = prompt('Enter new filename (e.g. itinerary.txt, notes.md):');
    if (!filename || !filename.trim()) return;

    try {
      await api.saveWorkspaceFile(filename.trim(), `# ${filename.trim()}\n`);
      await loadFiles();
      handleOpenFile(filename.trim());
    } catch (err) {
      alert('Failed to create file: ' + err.message);
    }
  };

  const handleDelete = async (filename) => {
    if (!confirm(`Delete file '${filename}'?`)) return;
    try {
      await api.deleteWorkspaceFile(filename);
      if (activeFile === filename) {
        setActiveFile(null);
        setContent('');
      }
      loadFiles();
    } catch (err) {
      alert('Failed to delete file: ' + err.message);
    }
  };

  return (
    <div>
      <div className="flex-between mb-6">
        <div>
          <h2>📁 Workspace File Explorer & Editor</h2>
          <p className="text-muted">Manage persistent files generated by agents, tools, itineraries, and shopping lists</p>
        </div>
        <button className="btn btn-primary btn-sm" onClick={handleCreatePrompt}>
          <Plus size={16} />
          <span>New File</span>
        </button>
      </div>

      <div className="charts-grid">
        {/* Files List */}
        <div className="glass-card">
          <div className="card-header flex-between">
            <h3>📂 Files in <code>./workspace</code></h3>
            <span className="badge badge-dim">{files.length} Files</span>
          </div>
          <div className="card-body p-0">
            <div className="table-responsive">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Filename</th>
                    <th>Size</th>
                    <th>Last Modified</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {files.length === 0 ? (
                    <tr>
                      <td colSpan={4} className="text-center py-6 text-muted">
                        No files in ./workspace directory yet.
                      </td>
                    </tr>
                  ) : (
                    files.map((f) => {
                      const sizeKb = (f.size_bytes / 1024).toFixed(1);
                      const dateStr = new Date(f.modified_time * 1000).toLocaleString();
                      const isActive = activeFile === f.filename;

                      return (
                        <tr key={f.filename} style={isActive ? { background: 'rgba(6, 182, 212, 0.08)' } : {}}>
                          <td>
                            <strong>📄 <code>{f.filename}</code></strong>
                          </td>
                          <td><span className="text-secondary text-sm">{sizeKb} KB</span></td>
                          <td><span className="text-muted text-sm">{dateStr}</span></td>
                          <td>
                            <div style={{ display: 'flex', gap: '6px' }}>
                              <button
                                className="btn btn-secondary btn-sm"
                                onClick={() => handleOpenFile(f.filename)}
                              >
                                <Edit3 size={14} />
                              </button>
                              <button
                                className="btn btn-secondary btn-sm"
                                onClick={() => handleDelete(f.filename)}
                              >
                                <Trash2 size={14} />
                              </button>
                            </div>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* File Editor */}
        <div className="glass-card">
          <div className="card-header flex-between">
            <h3>{activeFile ? `📄 Editing: ${activeFile}` : '📄 File Editor'}</h3>
            {activeFile && (
              <div style={{ display: 'flex', gap: '8px' }}>
                <button className="btn btn-secondary btn-sm" onClick={handleDownload}>
                  <Download size={14} />
                  <span>Download</span>
                </button>
                <button className="btn btn-primary btn-sm" onClick={handleSaveFile}>
                  <Save size={14} />
                  <span>Save</span>
                </button>
              </div>
            )}
          </div>
          <div className="card-body">
            {activeFile ? (
              <textarea
                className="form-control code-font"
                rows={18}
                value={content}
                onChange={(e) => setContent(e.target.value)}
                style={{ resize: 'vertical' }}
              />
            ) : (
              <div className="text-center py-6 text-muted">
                Select a file on the left or click <strong>New File</strong> to view and edit.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
