import React from 'react';
import { RefreshCw } from 'lucide-react';

const TAB_TITLES = {
  chat: { title: 'AI Agent Chatbot', subtitle: 'Interactive ReAct Agent with Everyday Tools, Domain Skills & Multi-Provider Gateway' },
  tools: { title: 'MCP Tools & Sandbox', subtitle: 'Directly inspect, parameterize, and execute Model Context Protocol tools in a live sandbox' },
  skills: { title: 'Domain Skills Hub', subtitle: 'Explore, customize, and create specialized agent personas with custom prompt injections' },
  workspace: { title: 'Workspace File Explorer', subtitle: 'Manage persistent files generated by agents, tools, itineraries, and shopping lists' },
  overview: { title: 'Telemetry & Metrics Observatory', subtitle: 'Real-time LLM inference audit trails, token telemetry & agent interactions' },
  logs: { title: 'Interaction Audit Logs', subtitle: 'Searchable historical prompts, responses, tool calls, and caller contexts' },
  evals: { title: 'Evals & Benchmarks', subtitle: 'Evaluate tool accuracy, skill adherence, and execution correctness across models' },
  settings: { title: 'Settings & Diagnostics', subtitle: 'Manage multi-provider API keys, Ollama base URLs, transport mode, and monitor host system metrics' }
};

export default function TopHeader({ activeTab, activeModel, onRefresh }) {
  const meta = TAB_TITLES[activeTab] || { title: 'Agentic AI Studio', subtitle: '' };

  return (
    <header className="topbar">
      <div className="topbar-left">
        <h1>{meta.title}</h1>
        <p>{meta.subtitle}</p>
      </div>
      <div className="topbar-actions">
        <div className="model-badge">
          <span className="dot-active"></span>
          <span>{activeModel || 'ollama/qwen2.5-coder:7b'}</span>
        </div>
        <button className="btn btn-secondary" onClick={onRefresh}>
          <RefreshCw size={16} />
          <span>Refresh</span>
        </button>
      </div>
    </header>
  );
}
